// One-off build script: NYC ZIP code centroids → lib/zips.ts
//
// Downloads the US Census ZCTA Gazetteer (national), keeps only the ZIP code
// tabulation areas whose centroid falls inside a NYC bounding box, and writes
// each ZIP's centroid lat/lng. The app uses these to map a typed ZIP code to
// the nearest gay-bar neighborhood (see lib/geo.ts `nearestNeighborhood`).
//
// Output is committed and read at runtime — the app stays static/offline.
// Re-run with `node scripts/build-zips.mjs`.

import { execFileSync } from "node:child_process";
import {
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// US Census 2023 ZCTA Gazetteer: a zipped, tab-delimited file with columns
// GEOID (ZCTA5), ALAND, AWATER, ALAND_SQMI, AWATER_SQMI, INTPTLAT, INTPTLONG.
const URL =
  "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2023_Gazetteer/2023_Gaz_zcta_national.zip";

// Numeric ZIP ranges that belong to the five boroughs. Used to exclude the
// neighbouring NJ (07xxx) and Nassau/Westchester ZIPs that share NYC's lat/lng.
const NYC_ZIP_RANGES = [
  [10001, 10292], // Manhattan
  [10301, 10314], // Staten Island
  [10451, 10475], // Bronx
  [11004, 11005], // Queens — Glen Oaks / Floral Park
  [11101, 11120], // Queens — LIC, Astoria, Sunnyside, Woodside, Maspeth
  [11201, 11256], // Brooklyn
  [11351, 11385], // Queens — Flushing, Corona, Jackson Heights, Ridgewood
  [11411, 11436], // Queens — southeast (Jamaica, Cambria Heights, etc.)
  [11691, 11697], // Queens — Rockaways
];

function isNycZip(zip) {
  const n = Number(zip);
  return NYC_ZIP_RANGES.some(([lo, hi]) => n >= lo && n <= hi);
}

// Sanity bounding box for the five boroughs (guards against odd centroids).
const NYC = { minLat: 40.48, maxLat: 40.93, minLng: -74.28, maxLng: -73.68 };

async function main() {
  const dir = mkdtempSync(join(tmpdir(), "nyc-zips-"));
  try {
    console.log(`Downloading ${URL} …`);
    const res = await fetch(URL, {
      headers: { "User-Agent": "nyc-gaybar-tracker/1.0 (build-time)" },
      signal: AbortSignal.timeout(60000),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const zipPath = join(dir, "zcta.zip");
    writeFileSync(zipPath, Buffer.from(await res.arrayBuffer()));

    // unzip to a single .txt; read whatever the archive contains.
    execFileSync("unzip", ["-o", "-d", dir, zipPath], { stdio: "ignore" });
    const txtName = readdirSync(dir).find((f) => f.endsWith(".txt"));
    if (!txtName) throw new Error("No .txt file in the gazetteer archive");
    // The gazetteer ships as latin1 (a few non-UTF8 place names); we only read
    // numeric/ASCII columns, so decode leniently.
    const txt = readFileSync(join(dir, txtName), "latin1");

    const lines = txt.split(/\r?\n/);
    const header = lines[0].split("\t").map((h) => h.trim());
    const iGeoid = header.indexOf("GEOID");
    const iLat = header.indexOf("INTPTLAT");
    const iLng = header.indexOf("INTPTLONG");
    if (iGeoid < 0 || iLat < 0 || iLng < 0) {
      throw new Error(`Unexpected gazetteer columns: ${header.join(", ")}`);
    }

    const zips = {};
    for (let i = 1; i < lines.length; i++) {
      const cols = lines[i].split("\t");
      if (cols.length <= iLng) continue;
      const zip = cols[iGeoid].trim();
      const lat = Number(cols[iLat]);
      const lng = Number(cols[iLng]);
      if (!/^\d{5}$/.test(zip) || Number.isNaN(lat) || Number.isNaN(lng)) {
        continue;
      }
      if (!isNycZip(zip)) continue;
      if (
        lat >= NYC.minLat &&
        lat <= NYC.maxLat &&
        lng >= NYC.minLng &&
        lng <= NYC.maxLng
      ) {
        zips[zip] = {
          lat: Number(lat.toFixed(5)),
          lng: Number(lng.toFixed(5)),
        };
      }
    }

    const sorted = Object.keys(zips).sort();
    const entries = sorted
      .map((z) => `  "${z}": { lat: ${zips[z].lat}, lng: ${zips[z].lng} },`)
      .join("\n");

    const body = `// Generated by scripts/build-zips.mjs — do not edit by hand.
// NYC ZIP code centroids (US Census 2023 ZCTA Gazetteer), used to map a typed
// ZIP code to the nearest gay-bar neighborhood. Re-run the script to refresh.

export type ZipCentroid = { lat: number; lng: number };

export const ZIP_CENTROIDS: Record<string, ZipCentroid> = {
${entries}
};
`;
    writeFileSync(join(ROOT, "lib", "zips.ts"), body);
    console.log(`Wrote ${sorted.length} NYC ZIP centroids to lib/zips.ts`);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
